Deploy to server
fingersi/testguru pull request #16
Opened 2023-01-22 17:08 UTC by fingersi

2023-02-09 11:18 UTC, BubuntuClu requested changes

2023-02-09 11:18 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +      flash.alert = 'Test has not been deleted. There are undeleted questions.'
это не решение проблемы. типа ты должен пойти и удалить сначала, все ответы, потом все вопросы и только потом тест? нет, так не пойдет. удаляя тест, все связнные с ним объекты должны быть удалены

2023-02-09 11:18 UTC, BubuntuClu commented on app/models/question.rb
> +  def self.answers?(questions)
сложное решение для текущей задачи. оно может быть как доп проверка, но не как основное

2023-02-09 11:18 UTC, BubuntuClu commented on app/models/test.rb
> +  def self.for_users
тебя понесло куда-то в космос на твоем проекте) все гораздо проще

2023-02-09 11:18 UTC, BubuntuClu commented on app/models/user.rb
> +  def self.find_sti_class(type_name)
эт что и зачем?

2023-02-13 17:53 UTC, fingersi commented on app/models/question.rb
> +  def self.answers?(questions)
У меня главное решение было не показывать пользователям не заполненные тесты. Для этого и понадобилась доп проверка.

2023-02-19 17:30 UTC, BubuntuClu commented on app/models/test.rb
> +  def destroy_associations
это решается через опцию `dependent` для ассоциаций. посмотри как это делается в доке

2023-02-19 17:30 UTC, BubuntuClu commented on app/models/test.rb
> +    Test.where(published: true)
это же скоуп, зачем оборачивать в метод?

2023-02-19 20:45 UTC, merged