added test_passing controller
fingersi/testguru pull request #8
Opened 2021-12-21 12:08 UTC by fingersi

2021-12-21 18:27 UTC, BubuntuClu requested changes

2021-12-21 18:27 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test_passing = TestPassing.new(user_id: User.second.id, test_id: @test.id, level: @test.level)
а что происходит в этом методе?

```
 def start
    @user.tests.push(@test)
    redirect_to @user.test_passage(@test)
  end
```
что-то у тебя совсем не то

2021-12-21 18:27 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    if @test_passing.save!
бэнг методы без `rescue` блока нельзя использовать

2021-12-21 18:27 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    respond_to do |format|
ты не поддерживаешь другие форматы кроме `html`, не надо их использовать. убери этот блок с распределением форматов

2021-12-21 18:27 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    respond_to do |format|
во всех экшенах надо это убрать

2021-12-21 18:27 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +      params.fetch(:test, {})
надо указать какие параметры разрешены для использования в тестах

2021-12-21 18:27 UTC, BubuntuClu commented on app/models/test.rb
> +  has_many :users, through: :test_passing
эта ассоциация сейчас не будет работать, ты не все заменил

2021-12-21 18:27 UTC, BubuntuClu commented on app/models/test_passing.rb
> +    self.current_question = next_question
>1. Сделайте назначение следующего вопроса в модели TestPassage с помощью обратного вызова

это задание не сделал

2021-12-21 18:27 UTC, BubuntuClu commented on app/views/test_passing/result.html.erb
> +<% mark = 0.0 %>
зачем эта строка?

2021-12-21 18:27 UTC, BubuntuClu commented on app/views/test_passing/result.html.erb
> +<% mark = @test_passing.correct_questions.to_f / @test_passing.test.questions.count.to_f * 100 %>
это можно сделать методом в модели, чтобы не тащить логику во вьюху
`test_passage.result`

2021-12-21 18:27 UTC, BubuntuClu commented on app/views/test_passing/result.html.erb
> +<% if mark >= 85%>
что такое 85? может 54 правильно? или 113? сейчас это просто магическое число, которое без контекста не понятно. ее стоит занести в модель и там в константу, дать константе понятное имя

2021-12-21 18:27 UTC, BubuntuClu commented on app/views/test_passing/result.html.erb
> +<% if mark >= 85%>
саму проверку стоит тоже поместить в метод модели `test_passage.success?`
внутри можно будет использовать `result`. таким образом ты сильно упростишь вьюху

2021-12-21 18:27 UTC, BubuntuClu commented on app/views/test_passing/result.html.erb
> +<h1><font size="6" color= <%= color%> face="serif">Test has been completed</font></h1>
сделай лучше разную верстку внутри ветвях `if`. чтобы еще и текст менялся, а не только цвет. 

либо можно сделать хэлпер, который вернет теме цвет и текст используй методы модели, а потом в верстку подставишь результат

2021-12-21 18:27 UTC, BubuntuClu commented on app/views/test_passing/show.html.erb
> +<p> Question number <%= questions_count - @test_passing.test.questions.order(:id).where('id > ?', @test_passing.current_question.id).count  %> of <%= questions_count %> </p>
на вьюхах не должно быть логики/запросов. метод сделай для получения текущего вопроса

2021-12-21 18:27 UTC, BubuntuClu commented on app/views/tests/_test.json.jbuilder
> +json.extract! test, :id, :created_at, :updated_at
json стоит выпилить, в текущем курсе мы его не проходим и не будем никак с ним взаимодейстоввать, так он не будет мешать в ПРах и при разработке

2021-12-21 18:27 UTC, BubuntuClu commented on app/views/tests/index.html.erb
> +    <% @tests.each do |test| %>
это можно в паршиал `_test` вынести, что бы было просто `render @tests`

2021-12-21 18:54 UTC, fingersi commented on app/controllers/tests_controller.rb
> +    @test_passing = TestPassing.new(user_id: User.second.id, test_id: @test.id, level: @test.level)
@user.tests.push(@test) - не работает в мое случае, из-за поля level в модели test_passing. Сохранялось на случай, если у теста измениться уровень.

2021-12-26 17:39 UTC, BubuntuClu requested changes

2021-12-26 17:39 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test_passing = TestPassing.new(user_id: User.second.id, test_id: @test.id, level: @test.level)
так уровень хранится в тесте, а не в прохождении. если изменился уровень теста, то как это аффектит прохождение?

мне кажется, ты сам себе проблему придумал)

2021-12-26 17:39 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    respond_to do |format|
форматы не убрал

2021-12-26 17:39 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    respond_to do |format|
и тут

2021-12-26 17:39 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +      format.html { redirect_to tests_url, notice: "Test was successfully destroyed." }
зачем блок если у тебя только один формат?

2021-12-26 17:39 UTC, BubuntuClu commented on app/helpers/test_passing_helper.rb
> +  def result_final_text(successfull)
объедини эти два метода в один. зачем одну проверку делать два раза? ты мообще можешь вернуть из этого метода просто текст и цвет. а верстка будет одна

2021-12-26 17:39 UTC, BubuntuClu commented on app/helpers/test_passing_helper.rb
> +  def result_final_text(successfull)
передавай явно сюда `test_passage` и у него вызывай метод првоерки

2021-12-26 17:39 UTC, BubuntuClu commented on app/models/test_passing.rb
> +    return true if mark >= 85
>что такое 85? может 54 правильно? или 113? сейчас это просто магическое число, которое без контекста не понятно. ее стоит занести в модель и там в константу, дать константе понятное имя

1 - не до конца поправил замечание
2 - что вернет выражение `mark >= 85`? правильно, оно вернет true/false, значит не надо самому писать тоже самое. просто выражение оставь в методе

2021-12-26 17:39 UTC, BubuntuClu commented on app/views/test_passing/result.html.erb
> +<%= result_mark(@test_passing.successfull?, @test_passing.mark) %>
ты можешь передать просто объект в метод как один параметр и внутри иметь доступ ко всему содержимому обхекта, вместо двух параметров, которые являются метода объекта

2021-12-27 17:10 UTC, BubuntuClu requested changes

2021-12-27 17:10 UTC, BubuntuClu commented on app/models/test_passing.rb
> +    mark >= 85
85 - должна быть константой в модели

2022-01-13 15:14 UTC, merged